// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSh2D4Mz7mUarKli-hkIh62_urw8twQhg',
    appId: '1:968278789850:android:595a44b07276b347145fe3',
    messagingSenderId: '968278789850',
    projectId: 'iirc-prod',
    storageBucket: 'iirc-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYB1iBmf1kYGIslozK5PMlIvUUhGFh4Ys',
    appId: '1:968278789850:ios:76bb97314baed230145fe3',
    messagingSenderId: '968278789850',
    projectId: 'iirc-prod',
    storageBucket: 'iirc-prod.appspot.com',
    iosClientId: '968278789850-au4j8mkrkcctgnjgn0ohr4h0ps9jttvg.apps.googleusercontent.com',
    iosBundleId: 'io.github.jogboms.iirc',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM_0KETvs3m5S2OR7nxptzsbLtQaAbWu0',
    appId: '1:968278789850:web:6c58629ea16e43b6145fe3',
    messagingSenderId: '968278789850',
    projectId: 'iirc-prod',
    authDomain: 'iirc-prod.firebaseapp.com',
    storageBucket: 'iirc-prod.appspot.com',
    measurementId: 'G-0P9T69SHBH',
  );
}
